version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: llajta_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: llajta_park_db
      TZ: America/La_Paz
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-time-zone=-04:00

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: llajta_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root_password
      DATABASE_NAME: llajta_park_db
      JWT_SECRET: your_secret_key # Added a JWT_SECRET for authentication
    depends_on:
      - db
    command: npm run start:prod
    volumes:
      - ./backend:/app
      - /app/node_modules