version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: llajta_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: llajta_park_db
      TZ: America/La_Paz
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-time-zone=-04:00